### ISSUE TITLE
大佬怎么搭建啊

### ISSUE THREAD

**Issue by haihaimx** [zyk-miao/open_flutter_music#1]

**Comment by zyk-miao** [comment]
首先你需要搭建一个mysql和minio,这俩个你可以先百度看看怎么搭建。

**Comment by haihaimx** [comment]
大佬mysq有然后对象储存可以用腾讯的吗

**Comment by haihaimx** [comment]
大佬弄好了

**Comment by haihaimx** [comment]
好嘞谢谢您

**Comment by zyk-miao** [comment]
后端部署见 [](https://github.com/zyk-miao/open_flutter_music_back#readme)

**Comment by zyk-miao** [comment]
后端部署见 ![](https://github.com/zyk-miao/open_flutter_music_back#readme)

**Comment by zyk-miao** [comment]
后端部署见 https://github.com/zyk-miao/open_flutter_music_back#readme
